initial code
0804robot/obstacle-detector pull request #2
Opened 2022-10-07 22:44 UTC by 1998-felix

Signed-off-by: 1998-felix <felix.gateru@gmail.com>

2022-10-08 00:05 UTC, SammyOina requested changes

2022-10-08 00:05 UTC, SammyOina commented on obstacle_detector.cpp
> +    set_threshold_right = right_threshold;
where are you using this

2022-10-08 00:05 UTC, SammyOina commented on obstacle_detector.cpp
> +    set_threshold_right = right_threshold;
same goes for other thresholds

2022-10-09 15:31 UTC, 0x6f736f646f requested changes
Should this be an ultrasonic wrapper of Obstacle dector?

2022-10-15 09:39 UTC, merged